### PR TITLE
chore(workflow): specific target directory in Test process action

### PR DESCRIPTION
**Pull request by HsiangNianian**

### CODE REVIEW

**Comment by fu050409** [comment]
@HsiangNianian Thanks for you contribution, however, we're using **required workflow** to ensure we won't merge some pull requests contains issues unexpectedly, which depend on GitHub branch rules. I think we should not do this.

**Comment by HsiangNianian** [comment]
> @HsiangNianian Thanks for you contribution, however, we're using **required workflow** to ensure we won't merge some pull requests contains issues unexpectedly, which depend on GitHub branch rules. I think we should not do this.

TL;DR I understand what you mean, and I highly recommend this approach, please allow me to explain this PR

In actions, especially _push_ and _pull_request_ events, _paths_ have been added to indicate that the _Test_ workflow will only be triggered __when the commit path contains the _src_ or _tests_ folders (i.e., both have been modified)__ 

This is done to reduce the unnecessary workflow overhead caused by file changes under other paths

**Comment by fu050409** [comment]
I have to say that I agree with your idea. I add this path check for my personal account too, however, I have to remove branch protect rule for ci checks since PRs without test checks cannot be merged. But there is no workaound to add a GitHub based rule to avoid our maintainers merging PRs that failed on test checks without branch protect rule.

**Comment by HsiangNianian** [comment]
> @HsiangNianian I have to say that I agree with your idea. I add this path check for my personal account too, however, I have to remove branch protect rule for ci checks since PRs without test checks cannot be merged. But there is no workaround to add a GitHub based rule to avoid our maintainers merging PRs that failed on test checks without branch protect rule.

I understand your concerns, but this is a harmless thing. You can try it. I suspect two outcomes: 1. The checks continue but are blocked or skipped. The contributor cannot set up automatic merger. 2, there is no test check, other workflows can be automatically merged after the check.

**Review by fu050409 — APPROVED** [review]

**Comment by fu050409** [comment]
@HsiangNianian Here's what actually happens:

 1. If we keep GitHub's branch protection policy in place, then if a change in a pr is not within the specified path, the corresponding ci check is not triggered. For example, we have a test check, which means that no member has permission to merge a pr that doesn't trigger this task, since passing the test check is mandatory. Even if it's not triggered, GitHub will assume that the pr didn't pass the expected check and block all merges.

2. If we remove the corresponding mandatory branch protection to allow PRs that don't triger a test check to be merged, then our maintainer might accidentally merge a pr that triggers but fails the test, and GitHub won't block the merge because passing the test isn't mandatory, even if it fails.

In the last change I think it makes sense, this at least reduces the overhead of the main branch. Overall, thanks for your contribution.

**Pull request merged**
